#!/bin/bash

source /opt/ros/indigo/setup.bash
source $HOME/catkin_ws/devel/setup.bash
$HOME/ROS-Box/tserv &
jupyter notebook --config=$HOME/ROS-Box/jupyter_notebook_config.py &
sleep 5 && conky --config=$HOME/ROS-Box/conkyrc &
